### ISSUE TITLE
Will there be any iOS client?

### ISSUE THREAD

**Issue by danialbehzadi** [kontalk/iosclient#2]
Is an iOS client in the roadmap?

**Comment by daniele-athome** [comment]
Not in the near future I'm afraid. Resources are already fully dedicated to existing maintenance and we don't really have a iOS developer yet. We might choose to hire one, but it really depends on donations.
If you have experience and would like to dedicate some time to a Kontalk iOS client (or you know someone who would) you are most welcome of course.
